version: 1.2
notebooks:
  - name: connecting
    path: /jupyter/examples/Connecting_with_the_Qt_Console.ipynb
    publish: true
  - name: custom
    path: /jupyter/examples/Custom_Keyboard_Shortcuts.ipynb
    publish: true
  - name: importing
    path: /jupyter/examples/Importing_Notebooks.ipynb
    publish: true
  - name: notebook
    path: /jupyter/examples/Notebook_Basics.ipynb
    publish: true
  - name: running
    path: /jupyter/examples/Running_Code.ipynb
    publish: true
  - name: typesetting
    path: /jupyter/examples/Typesetting_Equations.ipynb
    publish: true
  - name: what
    path: /jupyter/examples/What_is_the_Jupyter_Notebook.ipynb
    publish: true
  - name: working
    path: /jupyter/examples/Working_With_Markdown_Cells.ipynb
    publish: true
  - name: ibm-senegal
    path: /ibm-et/jupyter-samples/united-nations/senegal_population_trends.ipynb
    publish: true
  - name: ibm-tax-maps
    path: /ibm-et/jupyter-samples/tax-maps/Interactive_Data_Maps.ipynb
    publish: true
    authors:
      - orcid: 0000-0002-6130-1021    
  - name: ibm-airline
    path: /ibm-et/jupyter-samples/airline/Exploration_of_Airline_On-Time_Performance.ipynb
    publish: true
    authors:
      - orcid: 0000-0002-6130-1021
  - name: ibm-mlb
    path: /ibm-et/jupyter-samples/mlb/mlb-salaries.ipynb
    publish: true
    authors:
      - orcid: 0000-0002-6130-1021

